apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base.yaml
  - routes.yaml
  - wtransport.yaml
  # - axum-server.yaml

configMapGenerator:
  - name: config
    envs:
      - .env

secretGenerator:
  - name: secret
    envs:
      - .env.local
