apiVersion: apps/v1
kind: Deployment
metadata:
  name: wtransfer-client
  labels:
    app.kubernetes.io/name: wtransfer-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wtransfer-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wtransfer-client
    spec:
      # imagePullSecrets:
      #   - name: regcred
      containers:
        - name: wtransfer-client
          image: docker.io/anhelinakruk/wtransfer-client
          envFrom:
            - secretRef:
                name: secret
            - configMapRef:
                name: config
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: wtransfer-client
spec:
  selector:
    app.kubernetes.io/name: wtransfer-client
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 5173
    - name: udp
      protocol: UDP
      port: 80
      targetPort: 5173
