apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wtransport-client
spec:
  parentRefs:
    - kind: Gateway
      name: nginx
      namespace: nginx-gateway
  hostnames:
    - anhelina.visoft.dev
  rules:
    - matches:
        - path:
            value: '/wtransport'
      backendRefs:
        - name: wtransport-server
          port: 4433
    - matches:
      backendRefs:
        - name: wtransport-client
          port: 4173
