apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wtransfer-client
  annotations:
    nginx.ingress.kubernetes.io/enable-early-hints: 'false'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
spec:
  parentRefs:
    - kind: Gateway
      name: nginx
      namespace: nginx-gateway
  hostnames:
    - anhelina.visoft.dev
  rules:
    - matches:
      backendRefs:
        - name: wtransfer-client
          port: 80
    - matches:
      backendRefs:
        - name: wtransfer-server
          port: 80
